<!DOCTYPE html>
<html lang="en">
  <!-- Beautiful Jekyll | MIT license | Copyright Dean Attali 2016 -->
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover">

  <title>UNSW LoL Society</title>

  <meta name="author" content="UNSWLoLSoc" />

  

  <link rel="alternate" type="application/rss+xml" title="UNSW LoL Society - UNSW League of Legends Society" href="/LoLSocWebpage/feed.xml" />

  

  
  

  
    
      
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" />

    
  

  
    
      <link rel="stylesheet" href="/LoLSocWebpage/css/bootstrap.min.css" />
    
      <link rel="stylesheet" href="/LoLSocWebpage/css/bootstrap-social.css" />
    
      <link rel="stylesheet" href="/LoLSocWebpage/css/main.css" />
    
  

  
    
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
    
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
    
  

  

  

  

    <!-- Facebook OpenGraph tags -->
  

  
  <meta property="og:title" content="UNSW LoL Society" />
  

   
  <meta property="og:description" content="--- url: http://xelus22.github.io/LoLSocWebpage baseurl: &quot;/LoLSocWebpage&quot; title: UNSW LoL Society description: UNSW League of Legends Society navbar-links: About Us: - Our Society: aboutus - Our Executives: ourexecs - Our Sponsors: oursponsors Discord: https://discord.gg/unswlolsoc Pages: - 2019 OWeek Callout: 2019O-WeekCallout Resources: - Newsletters: newsletters/index.html - Events: events/index.html - Esports Corner: https://pages.github.com/ Sign...">
  


  <meta property="og:type" content="website" />

  
  <meta property="og:url" content="http://xelus22.github.io/LoLSocWebpage/config-forestryio.yml" />
  <link rel="canonical" href="http://xelus22.github.io/LoLSocWebpage/config-forestryio.yml" />
  

  
  <meta property="og:image" content="http://xelus22.github.io/LoLSocWebpage/img/lolsoc_dark.jpg" />
  


  <!-- Twitter summary cards -->
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@" />
  <meta name="twitter:creator" content="@" />

  
  <meta name="twitter:title" content="UNSW LoL Society" />
  

  
  <meta name="twitter:description" content="--- url: http://xelus22.github.io/LoLSocWebpage baseurl: &quot;/LoLSocWebpage&quot; title: UNSW LoL Society description: UNSW League of Legends Society navbar-links: About Us: - Our Society: aboutus - Our Executives: ourexecs - Our Sponsors: oursponsors Discord: https://discord.gg/unswlolsoc Pages: - 2019 OWeek Callout: 2019O-WeekCallout Resources: - Newsletters: newsletters/index.html - Events: events/index.html - Esports Corner: https://pages.github.com/ Sign...">
  

  
  <meta name="twitter:image" content="http://xelus22.github.io/LoLSocWebpage/img/lolsoc_dark.jpg" />
  

  

</head>


  <body>

    
  
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
        <a class="navbar-brand" href="http://xelus22.github.io/LoLSocWebpage">UNSW LoL Society</a>
      
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
          <li class="navlinks-container">
            <a class="navlinks-parent" href="javascript:void(0)">About Us</a>
            <div class="navlinks-children">
              
                
                  






<a href="/LoLSocWebpage/aboutus">Our Society</a>

                
              
                
                  






<a href="/LoLSocWebpage/ourexecs">Our Executives</a>

                
              
                
                  






<a href="/LoLSocWebpage/oursponsors">Our Sponsors</a>

                
              
            </div>
          </li>
        
        
        
          <li>
            






<a href="https://discord.gg/unswlolsoc">Discord</a>

          </li>
        
        
        
          <li class="navlinks-container">
            <a class="navlinks-parent" href="javascript:void(0)">Pages</a>
            <div class="navlinks-children">
              
                
                  






<a href="/LoLSocWebpage/2019O-WeekCallout">2019 OWeek Callout</a>

                
              
            </div>
          </li>
        
        
        
          <li class="navlinks-container">
            <a class="navlinks-parent" href="javascript:void(0)">Resources</a>
            <div class="navlinks-children">
              
                
                  






<a href="/LoLSocWebpage/newsletters/index.html">Newsletters</a>

                
              
                
                  






<a href="/LoLSocWebpage/events/index.html">Events</a>

                
              
                
                  






<a href="https://pages.github.com/">Esports Corner</a>

                
              
            </div>
          </li>
        
        
        
          <li>
            






<a href="/LoLSocWebpage/signup">Sign Up</a>

          </li>
        
        
        
          <li>
            






<a href="/LoLSocWebpage/contactus">Contact Us</a>

          </li>
        
        
      </ul>
    </div>

	
	<div class="avatar-container">
	  <div class="avatar-img-border">
	    <a href="http://xelus22.github.io/LoLSocWebpage ">
	      <img class="avatar-img" src="/LoLSocWebpage/img/lolsoc_dark.jpg" />
		</a>
	  </div>
	</div>
	

  </div>
</nav>


    <!-- TODO this file has become a mess, refactor it -->


<div class="intro-header"></div>


<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      ---
url: http://xelus22.github.io/LoLSocWebpage
baseurl: "/LoLSocWebpage"
title: UNSW LoL Society
description: UNSW League of Legends Society
navbar-links:
  About Us:
  - Our Society: aboutus
  - Our Executives: ourexecs
  - Our Sponsors: oursponsors
  Discord: https://discord.gg/unswlolsoc
  Pages:
  - 2019 OWeek Callout: 2019O-WeekCallout
  Resources:
  - Newsletters: newsletters/index.html
  - Events: events/index.html
  - Esports Corner: https://pages.github.com/
  Sign Up: signup
  Contact Us: contactus
avatar: "/img/lolsoc_dark.jpg"
navbar-col: "#000000"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#000000"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#000000"
footer-text-col: "#FFFFFF"
footer-link-col: "#000000"
author:
  name: UNSWLoLSoc
social-network-links:
  youtube: user/unswlolsoc
  email: unswlolsoc@gmail.com
  facebook: UNSWLoLSociety
  twitter: unswlolsoc
  instagram: UNSWLoLSoc
share-links-active:
  twitter: true
  facebook: true
  email: true
  google: false
excerpt_length: 70
title-separator: "-"
timezone: Australia/Sydney
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate_multiple:
- paginate: 5
  paginate_path: "/page:num"
  sub_dir: "/general"
- paginate: 10
  paginate_path: "/newsletters/page:num"
  sub_dir: "/newsletters"
- paginate: 10
  paginate_path: "/events/page:num"
  sub_dir: "/events"
kramdown:
  input: GFM
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: false
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  - "/vendor"
  - "/.bundle"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-menus
- jekyll-paginate-multiple

	    
    </div>
  </div>
</div>


    <footer>
  <div class="container beautiful-jekyll-footer">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links"><li><a href="https://www.youtube.com/user/unswlolsoc" title="YouTube"><span class="fa-stack fa-lg" aria-hidden="true">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                </span>
                <span class="sr-only">YouTube</span>
              </a>
            </li><li><a href="mailto:unswlolsoc@gmail.com" title="Email me"><span class="fa-stack fa-lg" aria-hidden="true">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                </span>
                <span class="sr-only">Email me</span>
              </a>
            </li><li><a href="https://www.facebook.com/UNSWLoLSociety" title="Facebook"><span class="fa-stack fa-lg" aria-hidden="true">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
                <span class="sr-only">Facebook</span>
              </a>
            </li><li><a href="https://twitter.com/unswlolsoc" title="Twitter"><span class="fa-stack fa-lg" aria-hidden="true">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                <span class="sr-only">Twitter</span>
              </a>
            </li><li><a href="https://www.instagram.com/UNSWLoLSoc" title="Instagram"><span class="fa-stack fa-lg" aria-hidden="true">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                </span>
                <span class="sr-only">Instagram</span>
              </a>
            </li></ul>
      <p class="copyright text-muted">
      UNSWLoLSoc
      &nbsp;&bull;&nbsp;
      2019

      

      
      </p>
          <!-- Please don't remove this, keep my open source work credited :) -->
    <p class="theme-by text-muted">
      Theme by
      <a href="https://deanattali.com/beautiful-jekyll/">beautiful-jekyll</a>
    </p>
      </div>
    </div>
  </div>
</footer>

  
    






  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
      <script>
      	if (typeof jQuery == 'undefined') {
      	  document.write('<script src="/LoLSocWebpage/js/jquery-1.11.2.min.js"></scr' + 'ipt>');
      	}
      </script>
    
  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
	<script src="/LoLSocWebpage/js/bootstrap.min.js"></script>
    
  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
	<script src="/LoLSocWebpage/js/main.js"></script>
    
  


  
  </body>
</html>
